"use client"

import { useApp } from "@/lib/app-context"
import { getStats } from "@/lib/data"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Download, FileSpreadsheet, BarChart3, FileText } from "lucide-react"

export function ExportReports() {
  const { complaints } = useApp()
  const stats = getStats(complaints)

  const handleCSVDownload = () => {
    const headers = ["ID", "Title", "Category", "Department", "Priority", "Status", "Ward", "Created"]
    const rows = complaints.map((c) => [
      c.id,
      `"${c.title}"`,
      c.category,
      c.department || c.category,
      c.priority,
      c.status,
      `"${(c.location as { area?: string })?.area ?? ""}",`,
      new Date(c.createdAt).toLocaleDateString("en-IN"),
    ])
    const csv = [headers.join(","), ...rows.map((r) => r.join(","))].join("\n")
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = `cityshakti-complaints-${new Date().toISOString().split("T")[0]}.csv`
    link.click()
    URL.revokeObjectURL(url)
  }

  const handleAnalyticsDownload = () => {
    // Calculate dynamic average resolution time for resolved complaints
    let avgDaysStr = "N/A"
    const resolvedComps = complaints.filter(c => c.status === "resolved")
    if (resolvedComps.length > 0) {
      const msDiff = resolvedComps.reduce((acc, current) => {
        return acc + (new Date(current.updatedAt).getTime() - new Date(current.createdAt).getTime())
      }, 0)
      const avgMs = msDiff / resolvedComps.length
      avgDaysStr = (avgMs / (1000 * 60 * 60 * 24)).toFixed(1) + " days"
    }

    const report = `
SMART CIVIC MONITORING SYSTEM - Analytics Report
Generated: ${new Date().toLocaleString("en-IN")}
================================================

SUMMARY
-------
Total Complaints: ${stats.total}
Resolved: ${stats.resolved} (${((stats.resolved / stats.total) * 100 || 0).toFixed(1)}%)
Pending: ${stats.pending} (${((stats.pending / stats.total) * 100 || 0).toFixed(1)}%)
In Progress: ${stats.inProgress} (${((stats.inProgress / stats.total) * 100 || 0).toFixed(1)}%)
Escalated: ${stats.escalated} (${((stats.escalated / stats.total) * 100 || 0).toFixed(1)}%)
High Priority: ${stats.highPriority}

RESOLUTION PERFORMANCE
----------------------
Overall Rate: ${((stats.resolved / stats.total) * 100 || 0).toFixed(1)}%
Average Response Time: ${avgDaysStr}

DEPARTMENT BREAKDOWN
--------------------
${["Public Works", "Water Supply", "Sanitation", "Electricity", "Roads & Transport", "Health Services", "Education", "Revenue", "General"]
        .map(
          (dept) =>
            `${dept}: ${complaints.filter((c) => c.department === dept).length} complaints`
        )
        .join("\n")}

RECOMMENDATION
--------------
- Focus on reducing pending complaints in high-density areas
- Increase officer allocation for Sanitation and Water Supply
- Implement proactive maintenance schedules

Report generated by SCMS AI Analytics Engine
    `.trim()

    const blob = new Blob([report], { type: "text/plain;charset=utf-8;" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = `scms-analytics-${new Date().toISOString().split("T")[0]}.txt`
    link.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="flex flex-col gap-6">
      <h2 className="text-lg font-semibold text-foreground">Export & Reports</h2>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {/* CSV Export */}
        <Card className="group hover:shadow-md transition-all">
          <CardContent className="flex flex-col items-center gap-4 p-6 text-center">
            <div className="rounded-2xl bg-chart-1/10 p-4">
              <FileSpreadsheet className="h-8 w-8 text-chart-1" />
            </div>
            <div>
              <h3 className="text-sm font-semibold text-foreground">
                Complaints Data (CSV)
              </h3>
              <p className="mt-1 text-xs text-muted-foreground">
                Download all {stats.total} complaints as a CSV spreadsheet
              </p>
            </div>
            <Button onClick={handleCSVDownload} className="w-full gap-2" size="sm">
              <Download className="h-4 w-4" />
              Download CSV
            </Button>
          </CardContent>
        </Card>

        {/* Analytics Report */}
        <Card className="group hover:shadow-md transition-all">
          <CardContent className="flex flex-col items-center gap-4 p-6 text-center">
            <div className="rounded-2xl bg-chart-2/10 p-4">
              <BarChart3 className="h-8 w-8 text-chart-2" />
            </div>
            <div>
              <h3 className="text-sm font-semibold text-foreground">
                Analytics Report
              </h3>
              <p className="mt-1 text-xs text-muted-foreground">
                Comprehensive analytics with department breakdown & insights
              </p>
            </div>
            <Button onClick={handleAnalyticsDownload} variant="outline" className="w-full gap-2" size="sm">
              <Download className="h-4 w-4" />
              Download Report
            </Button>
          </CardContent>
        </Card>

        {/* Quick stats */}
        <Card className="group hover:shadow-md transition-all">
          <CardContent className="flex flex-col items-center gap-4 p-6 text-center">
            <div className="rounded-2xl bg-chart-4/10 p-4">
              <FileText className="h-8 w-8 text-chart-4" />
            </div>
            <div>
              <h3 className="text-sm font-semibold text-foreground">
                Quick Summary
              </h3>
              <div className="mt-2 grid grid-cols-2 gap-2 text-left">
                <div className="rounded-lg bg-secondary px-3 py-2">
                  <span className="text-lg font-bold text-foreground">{stats.total}</span>
                  <p className="text-[10px] text-muted-foreground">Total</p>
                </div>
                <div className="rounded-lg bg-secondary px-3 py-2">
                  <span className="text-lg font-bold text-success">{stats.resolved}</span>
                  <p className="text-[10px] text-muted-foreground">Resolved</p>
                </div>
                <div className="rounded-lg bg-secondary px-3 py-2">
                  <span className="text-lg font-bold text-chart-4">{stats.pending}</span>
                  <p className="text-[10px] text-muted-foreground">Pending</p>
                </div>
                <div className="rounded-lg bg-secondary px-3 py-2">
                  <span className="text-lg font-bold text-destructive">{stats.highPriority}</span>
                  <p className="text-[10px] text-muted-foreground">High Priority</p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
